export * from './gestinDeDietasYAsignacinAClientes.service';
import { GestinDeDietasYAsignacinAClientesService } from './gestinDeDietasYAsignacinAClientes.service';
export * from './gestinDeEjerciciosYRutinas.service';
import { GestinDeEjerciciosYRutinasService } from './gestinDeEjerciciosYRutinas.service';
export * from './gestinDeEntrenamientos.service';
import { GestinDeEntrenamientosService } from './gestinDeEntrenamientos.service';
export * from './gestinDeInformacinDeSesionesDeLosClientes.service';
import { GestinDeInformacinDeSesionesDeLosClientesService } from './gestinDeInformacinDeSesionesDeLosClientes.service';
export * from './gestinDeUsuarios.service';
import { GestinDeUsuariosService } from './gestinDeUsuarios.service';
export * from './gestionDeCentrosYGerentes.service';
import { GestionDeCentrosYGerentesService } from './gestionDeCentrosYGerentes.service';
export * from './gestionDeClientesYMensajes.service';
import { GestionDeClientesYMensajesService } from './gestionDeClientesYMensajes.service';
export * from './gestionDeEntrenadoresYSusMensajes.service';
import { GestionDeEntrenadoresYSusMensajesService } from './gestionDeEntrenadoresYSusMensajes.service';
export * from './gestionDelCalendarioDeEntrenadores.service';
import { GestionDelCalendarioDeEntrenadoresService } from './gestionDelCalendarioDeEntrenadores.service';
export const APIS = [GestinDeDietasYAsignacinAClientesService, GestinDeEjerciciosYRutinasService, GestinDeEntrenamientosService, GestinDeInformacinDeSesionesDeLosClientesService, GestinDeUsuariosService, GestionDeCentrosYGerentesService, GestionDeClientesYMensajesService, GestionDeEntrenadoresYSusMensajesService, GestionDelCalendarioDeEntrenadoresService];
