/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DietaDTO } from '../model/dietaDTO';
import { DietaNuevaDTO } from '../model/dietaNuevaDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GestinDeDietasYAsignacinAClientesService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Actualiza una dieta. Solo puede hacerlo el entrenador que la ha creado.
     * @param body 
     * @param idDieta 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public actualizarDieta(body: DietaDTO, idDieta: number, observe?: 'body', reportProgress?: boolean): Observable<DietaDTO>;
    public actualizarDieta(body: DietaDTO, idDieta: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DietaDTO>>;
    public actualizarDieta(body: DietaDTO, idDieta: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DietaDTO>>;
    public actualizarDieta(body: DietaDTO, idDieta: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling actualizarDieta.');
        }

        if (idDieta === null || idDieta === undefined) {
            throw new Error('Required parameter idDieta was null or undefined when calling actualizarDieta.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DietaDTO>('put',`${this.basePath}/dieta/${encodeURIComponent(String(idDieta))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Permite asociar una dieta a un cliente. Solo lo puede hacer el entrenador que entrena al cliente.
     * @param body 
     * @param cliente 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public asociarDieta(body: DietaDTO, cliente: number, observe?: 'body', reportProgress?: boolean): Observable<DietaDTO>;
    public asociarDieta(body: DietaDTO, cliente: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DietaDTO>>;
    public asociarDieta(body: DietaDTO, cliente: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DietaDTO>>;
    public asociarDieta(body: DietaDTO, cliente: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling asociarDieta.');
        }

        if (cliente === null || cliente === undefined) {
            throw new Error('Required parameter cliente was null or undefined when calling asociarDieta.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cliente !== undefined && cliente !== null) {
            queryParameters = queryParameters.set('cliente', <any>cliente);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DietaDTO>('put',`${this.basePath}/dieta`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Permite crear una dieta a un entrenador. Solo lo puede hacer el entrenador.
     * @param body 
     * @param entrenador 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public crearDieta(body: DietaNuevaDTO, entrenador: number, observe?: 'body', reportProgress?: boolean): Observable<DietaDTO>;
    public crearDieta(body: DietaNuevaDTO, entrenador: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DietaDTO>>;
    public crearDieta(body: DietaNuevaDTO, entrenador: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DietaDTO>>;
    public crearDieta(body: DietaNuevaDTO, entrenador: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling crearDieta.');
        }

        if (entrenador === null || entrenador === undefined) {
            throw new Error('Required parameter entrenador was null or undefined when calling crearDieta.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (entrenador !== undefined && entrenador !== null) {
            queryParameters = queryParameters.set('entrenador', <any>entrenador);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DietaDTO>('post',`${this.basePath}/dieta`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Elimina la dieta. Solo puede hacerlo el entrenador que la ha creado.
     * @param idDieta 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eliminarDieta(idDieta: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public eliminarDieta(idDieta: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public eliminarDieta(idDieta: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public eliminarDieta(idDieta: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idDieta === null || idDieta === undefined) {
            throw new Error('Required parameter idDieta was null or undefined when calling eliminarDieta.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/dieta/${encodeURIComponent(String(idDieta))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Obtiene una dieta concreta. Solo puede hacerlo el entrenador que la ha creado y los clientes que entrena.
     * @param idDieta 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDieta(idDieta: number, observe?: 'body', reportProgress?: boolean): Observable<DietaDTO>;
    public getDieta(idDieta: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DietaDTO>>;
    public getDieta(idDieta: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DietaDTO>>;
    public getDieta(idDieta: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idDieta === null || idDieta === undefined) {
            throw new Error('Required parameter idDieta was null or undefined when calling getDieta.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DietaDTO>('get',`${this.basePath}/dieta/${encodeURIComponent(String(idDieta))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Permite consultar las dietas de un entrenador o la dieta asociada a un cliente, dependiento del parámetro de consulta. Se debe especificar exactamente un parámetro de consulta: entrenador o cliente. Cuando se especifica el entrenador la consula termina con éxito solo si es el entrenador quien accede. Cuando se especifica el cliente, solo puede acceder el cliente o el a quien pertenece la dieta.
     * @param entrenador 
     * @param cliente 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerDietas(entrenador?: number, cliente?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<DietaDTO>>;
    public obtenerDietas(entrenador?: number, cliente?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DietaDTO>>>;
    public obtenerDietas(entrenador?: number, cliente?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DietaDTO>>>;
    public obtenerDietas(entrenador?: number, cliente?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (entrenador !== undefined && entrenador !== null) {
            queryParameters = queryParameters.set('entrenador', <any>entrenador);
        }
        if (cliente !== undefined && cliente !== null) {
            queryParameters = queryParameters.set('cliente', <any>cliente);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DietaDTO>>('get',`${this.basePath}/dieta`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
