/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { SesionDTO } from '../model/sesionDTO';
import { SesionNuevaDTO } from '../model/sesionNuevaDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GestinDeInformacinDeSesionesDeLosClientesService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Actualiza una sesión de entrenamiento.
     * @param body 
     * @param idSesion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public actualizarSesion(body: SesionDTO, idSesion: number, observe?: 'body', reportProgress?: boolean): Observable<SesionDTO>;
    public actualizarSesion(body: SesionDTO, idSesion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SesionDTO>>;
    public actualizarSesion(body: SesionDTO, idSesion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SesionDTO>>;
    public actualizarSesion(body: SesionDTO, idSesion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling actualizarSesion.');
        }

        if (idSesion === null || idSesion === undefined) {
            throw new Error('Required parameter idSesion was null or undefined when calling actualizarSesion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SesionDTO>('put',`${this.basePath}/sesion/${encodeURIComponent(String(idSesion))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Permite crear una nueva sesión a un plan. 
     * @param body 
     * @param plan 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public crearSesion(body: SesionNuevaDTO, plan: number, observe?: 'body', reportProgress?: boolean): Observable<SesionDTO>;
    public crearSesion(body: SesionNuevaDTO, plan: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SesionDTO>>;
    public crearSesion(body: SesionNuevaDTO, plan: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SesionDTO>>;
    public crearSesion(body: SesionNuevaDTO, plan: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling crearSesion.');
        }

        if (plan === null || plan === undefined) {
            throw new Error('Required parameter plan was null or undefined when calling crearSesion.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (plan !== undefined && plan !== null) {
            queryParameters = queryParameters.set('plan', <any>plan);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SesionDTO>('post',`${this.basePath}/sesion`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Elimina la sesión de entrenamiento.
     * @param idSesion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public eliminarSesion(idSesion: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public eliminarSesion(idSesion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public eliminarSesion(idSesion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public eliminarSesion(idSesion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSesion === null || idSesion === undefined) {
            throw new Error('Required parameter idSesion was null or undefined when calling eliminarSesion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/sesion/${encodeURIComponent(String(idSesion))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Obtiene los detalles de la sesión especificada.
     * @param idSesion 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSesion(idSesion: number, observe?: 'body', reportProgress?: boolean): Observable<SesionDTO>;
    public getSesion(idSesion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SesionDTO>>;
    public getSesion(idSesion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SesionDTO>>;
    public getSesion(idSesion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSesion === null || idSesion === undefined) {
            throw new Error('Required parameter idSesion was null or undefined when calling getSesion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SesionDTO>('get',`${this.basePath}/sesion/${encodeURIComponent(String(idSesion))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Permite consultar las sesiones asociadas a un plan. Solo pueden acceder a ella el entrenador y el cliente relacionados con el plan.
     * @param plan 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public obtenerAsignaciones(plan: number, observe?: 'body', reportProgress?: boolean): Observable<Array<SesionDTO>>;
    public obtenerAsignaciones(plan: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SesionDTO>>>;
    public obtenerAsignaciones(plan: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SesionDTO>>>;
    public obtenerAsignaciones(plan: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (plan === null || plan === undefined) {
            throw new Error('Required parameter plan was null or undefined when calling obtenerAsignaciones.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (plan !== undefined && plan !== null) {
            queryParameters = queryParameters.set('plan', <any>plan);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<SesionDTO>>('get',`${this.basePath}/sesion`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
