/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ClienteNuevoDTO { 
    idUsuario?: number;
    telefono?: string;
    direccion?: string;
    dni?: string;
    fechaNacimiento?: Date;
    sexo?: ClienteNuevoDTO.SexoEnum;
}
export namespace ClienteNuevoDTO {
    export type SexoEnum = 'HOMBRE' | 'MUJER' | 'OTRO';
    export const SexoEnum = {
        HOMBRE: 'HOMBRE' as SexoEnum,
        MUJER: 'MUJER' as SexoEnum,
        OTRO: 'OTRO' as SexoEnum
    };
}