/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DestinatarioDTO { 
    id?: number;
    tipo?: DestinatarioDTO.TipoEnum;
}
export namespace DestinatarioDTO {
    export type TipoEnum = 'CENTRO' | 'ENTRENADOR' | 'CLIENTE';
    export const TipoEnum = {
        CENTRO: 'CENTRO' as TipoEnum,
        ENTRENADOR: 'ENTRENADOR' as TipoEnum,
        CLIENTE: 'CLIENTE' as TipoEnum
    };
}