/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EntrenadorNuevoDTO { 
    idUsuario?: number;
    telefono?: string;
    direccion?: string;
    dni?: string;
    fechaNacimiento?: Date;
    fechaAlta?: Date;
    fechaBaja?: Date;
    especialidad?: string;
    titulacion?: string;
    experiencia?: string;
    observaciones?: string;
}