/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EventoNuevoDTO { 
    nombre?: string;
    descripcion?: string;
    observaciones?: string;
    lugar?: string;
    duracionMinutos?: number;
    inicio?: Date;
    reglaRecurrencia?: string;
    idCliente?: number;
    tipo?: EventoNuevoDTO.TipoEnum;
}
export namespace EventoNuevoDTO {
    export type TipoEnum = 'DISPONIBILIDAD' | 'CITA';
    export const TipoEnum = {
        DISPONIBILIDAD: 'DISPONIBILIDAD' as TipoEnum,
        CITA: 'CITA' as TipoEnum
    };
}